CC        := gcc
CFLAGS    := -Wall -Wextra -O2 -std=gnu11 -MMD -MP

SRC_DIR   := src
BUILD_DIR := build

# ---- the three programs ----
PLAIN_SENDER   := $(BUILD_DIR)/sender      # old, plain TCP, no protection
PLAIN_RECEIVER := $(BUILD_DIR)/receiver    # old, plain TCP, no protection
AES_TARGET     := $(BUILD_DIR)/network     # new, AES-256-GCM protected

# ---- which object files go into which program ----
PLAIN_SENDER_OBJS   := $(BUILD_DIR)/sender.o
PLAIN_RECEIVER_OBJS := $(BUILD_DIR)/receiver.o
AES_OBJS            := $(BUILD_DIR)/main.o \
                       $(BUILD_DIR)/senderAES.o \
                       $(BUILD_DIR)/receiverAES.o

ALL_OBJS := $(PLAIN_SENDER_OBJS) $(PLAIN_RECEIVER_OBJS) $(AES_OBJS)
DEPS     := $(ALL_OBJS:.o=.d)

# default: build everything
all: $(PLAIN_SENDER) $(PLAIN_RECEIVER) $(AES_TARGET)

# shortcuts: build only one group
plain: $(PLAIN_SENDER) $(PLAIN_RECEIVER)
aes: $(AES_TARGET)

# ---- linking ----
# The plain programs do not need OpenSSL.
$(PLAIN_SENDER): $(PLAIN_SENDER_OBJS)
	$(CC) $^ -o $@

$(PLAIN_RECEIVER): $(PLAIN_RECEIVER_OBJS)
	$(CC) $^ -o $@

# Only the AES program needs -lcrypto (the OpenSSL library).
$(AES_TARGET): $(AES_OBJS)
	$(CC) $^ -o $@ -lcrypto

# ---- compiling: every .c becomes a .o ----
# "| $(BUILD_DIR)" makes sure the build/ folder exists first.
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

clean:
	rm -f $(ALL_OBJS) $(DEPS) $(PLAIN_SENDER) $(PLAIN_RECEIVER) $(AES_TARGET)

# header dependencies generated by -MMD: editing a .h rebuilds the right .c files
-include $(DEPS)

.PHONY: all plain aes clean
